repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  # Optional: Only run tests if pytest is available
  # Uncomment the section below if you want tests to run on commit
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: python -m pytest tests/
  #       language: system
  #       pass_filenames: false
  #       always_run: true
